homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  
  # Location required to calculate the time the sun rises and sets
  latitude: _REDACTED_
  longitude: _REDACTED_
  
  # Impacts weather/sunrise data (altitude above sea level) 
  elevation: _REDACTED_
  
  # 'metric' for the metric system, 'imperial' for the imperial system
  unit_system: imperial
  
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Chicago

  customize: !include customize.yaml

# Enables the frontend
frontend:

# Checks for available updates
updater:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Allows you to issue voice commands from the frontend
conversation:

# Enables support for tracking state changes over time.
history:

# Discover some devices automatically
discovery:

# Show links to resources in log and frontend
# introduction:

http:
  api_password: _REDACTED_
  ssl_certificate: _REDACTED_
  ssl_key: _REDACTED_
  approved_ips:
    - 127.0.0.1
    - _REDACTED_

#################################################################
## Components
#################################################################

ecobee:
  api_key: _REDACTED_
  hold_temp: True

light:
  platform: hue
  host: _REDACTED_
  allow_unreachable: true
  scan_interval: 10
  
emulated_hue:
  host_ip: _REDACTED_
  listen_port: _REDACTED_
  off_maps_to_on_domains:
    - script
    - scene
  expose_by_default: false

media_player:
  platform: plex

ifttt:
  key: _REDACTED_

device_tracker:
  - platform: locative
    track_new_devices: yes
    interval_seconds: 12
    consider_home: 180
  - platform: asuswrt
    host: _REDACTED_
    username: _REDACTED_
    password: _REDACTED_
 
cover:
  platform: myq
  name: Garage Door
  username: _REDACTED_
  password: _REDACTED_
  brand: chamberlain

camera:
  platform: foscam
  ip: _REDACTED_
  name: Garage Camera
  port: _REDACTED_
  username: _REDACTED_
  password: _REDACTED_

wink:
  email: _REDACTED_
  password: _REDACTED_
  client_id: _REDACTED_
  client_secret: _REDACTED_

recorder:
  purge_days: 30

ios:
  push_categories: # Defines actionable notifications. Categories are groups of actions. You specify the category in the notification.
    - name: Alarm
      identifier: 'ALARM' # Must be unique and ALL CAPS
      actions:
        - identifier: 'SOUND_ALARM' # Must be unique and ALL CAPS
          title: 'Sound Alarm' # Needs to be short!
          activationMode: 'background' # or background. The mode in which to run the app when the action is performed.
          authenticationRequired: yes # A Boolean value indicating whether the user must unlock the device before the action is performed.
          destructive: yes # A Boolean value indicating whether the action is destructive.  When the value of this property is true, the system displays the corresponding button differently to indicate that the action is destructive.
          behavior: 'default' # or TextInput. When TextInput the system provides a way for the user to enter a text response to be included with the notification.
          context: 'default' # or Minimal. Default = In this context, the full UI is displayed for the notification’s alert. You may specify up to four custom actions in this context. Minimal = In this context, a minimal UI is displayed for the notification’s alert. You may specify up to two custom actions in this context.
        - identifier: 'SILENCE_ALARM' # Must be unique and ALL CAPS
          title: 'Silence Alarm' # Needs to be short!
          activationMode: 'background' # or background. The mode in which to run the app when the action is performed.
          authenticationRequired: yes # A Boolean value indicating whether the user must unlock the device before the action is performed.
          destructive: no # A Boolean value indicating whether the action is destructive.  When the value of this property is true, the system displays the corresponding button differently to indicate that the action is destructive.
          behavior: 'TextInput' # Default or TextInput. When TextInput the system provides a way for the user to enter a text response to be included with the notification.
          context: 'default' # or Minimal. Default = In this context, the full UI is displayed for the notification’s alert. You may specify up to four custom actions in this context. Minimal = In this context, a minimal UI is displayed for the notification’s alert. You may specify up to two custom actions in this context.
          textInputButtonTitle: 'Silencio!' # Only for iOS 10 when behavior is TextInput.
          textInputPlaceholder: '...' # Only for iOS 10 when behavior is TextInput.
          parameters: # iOS 9 only. Use this dictionary to specify any behavior-specific data for the action. For example, if you set behavior to TextInput you can use the UIUserNotificationTextInputActionButtonTitleKey key, which lets you customize the title of the button displayed by the text input interface.
            UIUserNotificationTextInputActionButtonTitleKey: "Silencio!"

notify:
  - name: iOSApp
    platform: ios
    target: _REDACTED_

sensor:
  platform: speedtest
  monitored_conditions:
    - ping
    - download
    - upload

sensor 2:
  platform: forecast
  api_key: _REDACTED_
  monitored_conditions:
    - summary
    - minutely_summary
    - hourly_summary
    - daily_summary
#    - icon
    - nearest_storm_distance
    - nearest_storm_bearing
    - precip_type
    - precip_intensity
    - precip_probability
    - temperature
    - apparent_temperature
    - dew_point
    - wind_speed
    - wind_bearing
    - cloud_cover
    - humidity
    - pressure
    - visibility
    - ozone

sensor 3:
  platform: cpuspeed
  name: CPU 

sensor 4:
  platform: systemmonitor
  resources:
    - type: memory_free
    - type: memory_use_percent
    - type: processor_use
    - type: since_last_boot

sensor 5:
  platform: plex
  name: _REDACTED_
  host: _REDACTED_
  port: 32400
  username: _REDACTED_
  password: _REDACTED_
  server: _REDACTED_

sensor 6:  
  platform: template
  sensors:
    back_door_sensor_batt:
      value_template: '{{ states.binary_sensor.back_door.attributes.battery_level }}'
      friendly_name: 'Back Door Sensor'
      unit_of_measurement: '%'
    basement_door_sensor_batt:
      value_template: '{{ states.binary_sensor.basement_door.attributes.battery_level }}'
      friendly_name: 'Basement Door Sensor'
      unit_of_measurement: '%'
    front_door_sensor_batt:
      value_template: '{{ states.binary_sensor.front_door.attributes.battery_level }}'
      friendly_name: 'Front Door Sensor'
      unit_of_measurement: '%'
    siren_batt:
      value_template: '{{ states.switch.siren.attributes.battery_level }}'
      friendly_name: 'Siren'
      unit_of_measurement: '%'
    front_door_lock_batt:
      value_template: '{{ states.lock.front_door.attributes.battery_level }}'
      friendly_name: 'Front Door Lock'
      unit_of_measurement: '%'
    back_door_lock_batt:
      value_template: '{{ states.lock.back_door.attributes.battery_level }}'
      friendly_name: 'Back Door Lock'
      unit_of_measurement: '%'
    basement_door_lock_batt:
      value_template: '{{ states.lock.basement_door.attributes.battery_level }}'
      friendly_name: 'Basement Door Lock'
      unit_of_measurement: '%'

#################################################################
## Zones
#################################################################

#################################################################
## Includes
#################################################################

group: !include groups.yaml

scene: !include scenes.yaml

automation: !include automation.yaml

input_boolean: !include input_boolean.yaml

input_select: !include input_select.yaml

