homeassistant:
  # Name of the location where Home Assistant is running
  name: Home

  # Location required to calculate the time the sun rises and sets
  latitude: _REDACTED_
  longitude: _REDACTED_

  # Impacts weather/sunrise data (altitude above sea level)
  elevation: _REDACTED_

  # 'metric' for the metric system, 'imperial' for the imperial system
  unit_system: imperial

  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Chicago

  customize: !include customize.yaml

# Enables the frontend
frontend:

# Checks for available updates
updater:
  reporting: no

# View all events in a logbook
logbook: !include logbook.yaml

# Track the sun
sun:

# Allows you to issue voice commands from the frontend
conversation:

# Enables support for tracking state changes over time.
history: !include history.yaml

# Discover some devices automatically
discovery:

# Show links to resources in log and frontend
# introduction:

http:
  api_password: _REDACTED_
  ssl_certificate: _REDACTED_
  ssl_key: _REDACTED_
  base_url: _REDACTED_
  trusted_networks:
    - 127.0.0.1
    - _REDACTED_/24
  ip_ban_enabled: True
  login_attempts_threshold: 5

#################################################################
## Components
#################################################################

ecobee:
  api_key: _REDACTED_
  hold_temp: True

light:
  platform: hue
  host: _REDACTED_
  allow_unreachable: true

emulated_hue:
  host_ip: _REDACTED_
  listen_port: 8300
  off_maps_to_on_domains:
    - script
    - scene
  expose_by_default: false

media_player:
  - platform: plex
  - platform: sonos
    hosts:
      - _REDACTED_
      - _REDACTED_
      - _REDACTED_
      - _REDACTED_
      - _REDACTED_
      - _REDACTED_
      - _REDACTED_
      - _REDACTED_

remote:
  - platform: harmony
    name: Media Center
    host: _REDACTED_

ios:

notify:
  - platform: ios

ifttt:
  key: _REDACTED_

device_tracker:
  - platform: asuswrt
    host: _REDACTED_
    username: _REDACTED_
    password: _REDACTED_
    track_new_devices: no
    interval_seconds: 12
  - platform: locative

cover:
  platform: myq
  name: Garage Door
  username: _REDACTED_
  password: _REDACTED_
  brand: chamberlain

camera:
  - platform: foscam
    ip: _REDACTED_
    name: Garage Camera
    port: _REDACTED_
    username: _REDACTED_
    password: _REDACTED_
  - platform: ffmpeg
    input: http://_REDACTED_/rtplive/_REDACTED_/playlist.m3u8
    name: 64 at _REDACTED_
    extra_arguments: '-headers "X-Forwarded-For: _REDACTED_"'

wink:
  email: _REDACTED_
  password: _REDACTED_
  client_id: _REDACTED_
  client_secret: _REDACTED_

recorder: !include recorder.yaml

tts:
  - platform: google

#################################################################
## Shell Commands
#################################################################

shell_command:
  export_ha_states: '/home/_REDACTED_/.homeassistant/hass_saved_states.py -act update_settings -sec {{ section }} -set {{ settings }} -val "{{ value }}"'
  import_ha_states: '/home/_REDACTED_/.homeassistant/hass_saved_states.py -act update_hass'

#################################################################
## Web Links
#################################################################

weblink:
  entities:
    - name: _REDACTED_
      url: http://_REDACTED_
      icon: mdi:video
    - name: _REDACTED_
      url: http://_REDACTED_
      icon: mdi:video
    - name: _REDACTED_
      url: http://_REDACTED_
      icon: mdi:video
    - name: _REDACTED_
      url: http://_REDACTED_
      icon: mdi:video
    - name: _REDACTED_
      url: http://_REDACTED_
      icon: mdi:video
    - name: _REDACTED_
      url: http://_REDACTED_
      icon: mdi:video
    - name: _REDACTED_
      url: http://_REDACTED_
      icon: mdi:video
    - name: _REDACTED_
      url: http://_REDACTED_
      icon: mdi:video

#################################################################
## Sensors
#################################################################

sensor:
  - platform: speedtest
    monitored_conditions:
      - ping
      - download
      - upload
  - platform: darksky
    api_key: _REDACTED_
    monitored_conditions:
      - summary
      - minutely_summary
      - hourly_summary
      - daily_summary
      - nearest_storm_distance
      - nearest_storm_bearing
      - precip_type
      - precip_intensity
      - precip_probability
      - temperature
      - apparent_temperature
      - dew_point
      - wind_speed
      - wind_bearing
      - cloud_cover
      - humidity
      - pressure
      - visibility
      - ozone
  - platform: cpuspeed
    name: CPU
  - platform: systemmonitor
    resources:
      - type: memory_free
      - type: memory_use_percent
      - type: processor_use
      - type: since_last_boot
  - platform: plex
    name: _REDACTED_
    host: _REDACTED_
    port: _REDACTED_
    username: _REDACTED_
    password: _REDACTED_
    server: _REDACTED_
  - platform: template
    sensors:
      back_door_sensor_batt:
        value_template: '{{ states.binary_sensor.back_door.attributes.battery_level }}'
        friendly_name: 'Back Door Sensor'
        unit_of_measurement: '%'
      basement_door_sensor_batt:
        value_template: '{{ states.binary_sensor.basement_door.attributes.battery_level }}'
        friendly_name: 'Basement Door Sensor'
        unit_of_measurement: '%'
      front_door_sensor_batt:
        value_template: '{{ states.binary_sensor.front_door.attributes.battery_level }}'
        friendly_name: 'Front Door Sensor'
        unit_of_measurement: '%'
      siren_batt:
        value_template: '{{ states.switch.siren.attributes.battery_level }}'
        friendly_name: 'Siren'
        unit_of_measurement: '%'
      front_door_lock_batt:
        value_template: '{{ states.lock.front_door.attributes.battery_level }}'
        friendly_name: 'Front Door Lock'
        unit_of_measurement: '%'
      back_door_lock_batt:
        value_template: '{{ states.lock.back_door.attributes.battery_level }}'
        friendly_name: 'Back Door Lock'
        unit_of_measurement: '%'
      basement_door_lock_batt:
        value_template: '{{ states.lock.basement_door.attributes.battery_level }}'
        friendly_name: 'Basement Door Lock'
        unit_of_measurement: '%'
      basement_drain_water_sensor_batt:
        value_template: '{{ states.binary_sensor.basement_drain_water_sensor_liquid_detected.attributes.battery_level }}'
        friendly_name: 'Basement Drain Water Sensor'
        unit_of_measurement: '%'
      sump_pump_water_sensor_batt:
        value_template: '{{ states.binary_sensor.sump_pump_water_sensor_liquid_detected.attributes.battery_level }}'
        friendly_name: 'Sump Pump Water Sensor'
        unit_of_measurement: '%'
  - platform: template
    sensors:
      media_center:
        value_template: '{{ states.remote.media_center.attributes.current_activity }}'
        friendly_name: 'Media Center'
  - platform: google_travel_time
    name: _REDACTED_ To Home
    api_key: _REDACTED_
    origin: device_tracker._REDACTED_
    destination: zone.home
  - platform: google_travel_time
    name: _REDACTED_ To Home
    api_key: _REDACTED_
    origin: device_tracker._REDACTED_
    destination: zone.home
  - platform: google_travel_time
    name: _REDACTED_ To _REDACTED_
    api_key: _REDACTED_
    origin: device_tracker._REDACTED_
    destination: zone.work_2
  - platform: google_travel_time
    name: _REDACTED_ To _REDACTED_
    api_key: _REDACTED_
    origin: device_tracker._REDACTED_
    destination: zone.work_3
  - platform: google_travel_time
    name: _REDACTED_ To _REDACTED_
    api_key: _REDACTED_
    origin: device_tracker._REDACTED_
    destination: zone.work
  - platform: command_line
    name: Wink Status Logfile
    command: "/home/_REDACTED_/.homeassistant/winkLogCheck.sh"
    scan_interval: 60

#################################################################
## Zones
#################################################################

zone:

  name: work
  latitude: _REDACTED_
  longitude: _REDACTED_
  radius: 300
  icon: mdi:hospital

zone 2:

  name: work
  latitude: _REDACTED_
  longitude: _REDACTED_
  radius: 300
  icon: mdi:hospital

zone 3:

  name: work
  latitude: _REDACTED_
  longitude: _REDACTED_
  radius: 300
  icon: mdi:hospital

zone 4:

  name: lake
  latitude: _REDACTED_
  longitude: _REDACTED_
  radius: 20000
  icon: mdi:beach

#################################################################
## Includes
#################################################################

group: !include groups.yaml

scene: !include scenes.yaml

automation: !include automation.yaml

input_boolean: !include input_boolean.yaml

input_select: !include input_select.yaml

script: !include scripts.yaml
