homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: _REDACTED_
  longitude: _REDACTED_
  # C for Celcius, F for Fahrenheit
  temperature_unit: F
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Chicago

  customize: !include customize.yaml

# Enables the frontend
frontend:

# Checks for available updates
updater:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Allows you to issue voice commands from the frontend
conversation:

# Enables support for tracking state changes over time.
history:

# Discover some devices automatically
discovery:

# Show links to resources in log and frontend
# introduction:

http:
  api_password: _REDACTED_
  ssl_certificate: _REDACTED_
  ssl_key: _REDACTED_

#################################################################
## Components
#################################################################

light:
  platform: hue
  host: _REDACTED_
  allow_unreachable: true
  scan_interval: 10

media_player:
  platform: plex

wink:
  access_token: _REDACTED_

ecobee:
  api_key: _REDACTED_
  hold_temp: True

ifttt:
  key: _REDACTED_

device_tracker:
  - platform: locative
    track_new_devices: yes
    interval_seconds: 12
    consider_home: 180
  - platform: asuswrt
    host: _REDACTED_
    protocol: telnet
    mode: router
    username: _REDACTED_
    password: _REDACTED_

garage_door:
  platform: myq
  name: Garage Door
  username: _REDACTED_
  password: _REDACTED_

camera:
  platform: foscam
  ip: _REDACTED_
  name: Garage Camera
  port: _REDACTED_
  username: _REDACTED_
  password: _REDACTED_

notify:
  platform: googlevoice
  username: _REDACTED_
  password: _REDACTED_
  name: text_message

recorder:
  purge_days: 31

sensor:
  platform: speedtest
  monitored_conditions:
    - ping
    - download
    - upload

sensor 2:
  platform: forecast
  api_key: _REDACTED_
  monitored_conditions:
    - summary
    - minutely_summary
    - hourly_summary
    - daily_summary
#    - icon
    - nearest_storm_distance
    - nearest_storm_bearing
    - precip_type
    - precip_intensity
    - precip_probability
    - temperature
    - apparent_temperature
    - dew_point
    - wind_speed
    - wind_bearing
    - cloud_cover
    - humidity
    - pressure
    - visibility
    - ozone

sensor 3:
  platform: cpuspeed
  name: CPU 

sensor 4:
  platform: systemmonitor
  resources:
    - type: memory_free
    - type: memory_use_percent
    - type: processor_use
    - type: since_last_boot

sensor 5:
  platform: plex
  name: _REDACTED_
  host: _REDACTED_
  port: _REDACTED_
  username: _REDACTED_
  password: _REDACTED_
  server: _REDACTED_

#################################################################
## Zones
#################################################################

zone:

  name: Work
  latitude: _REDACTED_
  longitude: _REDACTED_
  radius: 250
  icon: mdi:hospital-building

zone 2:

  name: Work
  latitude: _REDACTED_
  longitude: _REDACTED_
  radius: 250
  icon: mdi:hospital-building

zone 3:

  name: Work
  latitude: _REDACTED_
  longitude: _REDACTED_
  radius: 250
  icon: mdi:hospital-building

#################################################################
## Includes
#################################################################

group: !include groups.yaml

scene: !include scenes.yaml

automation: !include automation.yaml

input_boolean: !include input_boolean.yaml
