#################################################################
## Home Assistant
#################################################################

homeassistant:
  name: Home
  latitude: _REDACTED_
  longitude: _REDACTED_
  elevation: _REDACTED_
  unit_system: imperial
  time_zone: America/Chicago
  customize: !include customize.yaml

frontend:
updater:
  reporting: no
sun:
conversation:
discovery:
config:

http:
  api_password: _REDACTED_
  ssl_certificate: _REDACTED_
  ssl_key: _REDACTED_
  base_url: _REDACTED_
  trusted_networks:
    - 127.0.0.1
    - _REDACTED_/24
    - _REDACTED_/24
  ip_ban_enabled: true
  login_attempts_threshold: 5

#################################################################
## Components
#################################################################

ecobee:
  api_key: _REDACTED_
  hold_temp: true

light:
  platform: hue
  host: _REDACTED_
  allow_unreachable: true

emulated_hue:
  host_ip: _REDACTED_
  listen_port: 8300
  type: alexa
  upnp_bind_multicast: false
  off_maps_to_on_domains:
    - script
    - scene
  expose_by_default: false

media_player:
  - platform: plex
  - platform: apple_tv
    host: _REDACTED_
    login_id: _REDACTED_
    name: Living Room Apple TV
  - platform: apple_tv
    host: _REDACTED_
    login_id: _REDACTED_
    name: _USER1_'s Office Apple TV
  - platform: apple_tv
    host: _REDACTED_
    login_id: _REDACTED_
    name: Bedroom Apple TV
  - platform: sonos
    hosts:
      - _REDACTED_
      - _REDACTED_
      - _REDACTED_
      - _REDACTED_
      - _REDACTED_
      - _REDACTED_
      - _REDACTED_
      - _REDACTED_

remote:
  - platform: harmony
    name: Media Center
    host: _REDACTED_

ios:

ifttt:
  key: _REDACTED_

device_tracker:
  - platform: asuswrt
    host: _REDACTED_
    username: _REDACTED_
    password: _REDACTED_
    protocol: telnet
    track_new_devices: no
    interval_seconds: 12
    consider_home: 180
  - platform: locative

cover:
  platform: myq
  name: Garage Door
  username: _REDACTED_
  password: _REDACTED_
  type: chamberlain

camera:
  - platform: foscam
    ip: _REDACTED_
    name: Garage Camera
    port: _REDACTED_
    username: _REDACTED_
    password: _REDACTED_
  - platform: ffmpeg
    input: http://_REDACTED_
    name: _REDACTED_
    extra_arguments: '-headers "X-Forwarded-For: _REDACTED_"'

wink:
  email: _REDACTED_
  password: _REDACTED_
  client_id: _REDACTED_
  client_secret: _REDACTED_

tts:
  - platform: google

#################################################################
## Includes
#################################################################

automation: !include_dir_merge_list automation
recorder: !include recorder.yaml
logbook: !include logbook.yaml
history: !include history.yaml
zone: !include zones.yaml
group: !include groups.yaml
scene: !include scenes.yaml
sensor: !include sensors.yaml
input_boolean: !include input_boolean.yaml
input_select: !include input_select.yaml
script: !include scripts.yaml
weblink: !include weblinks.yaml
shell_command: !include shell_commands.yaml
