#################################################################
## Weather Based Automations
#################################################################

        ##########################################################
        ## Turn On First Floor Lights During Rain
        ##########################################################

- alias: Weather - Rain First Floor Lights On

  trigger:
    - platform: numeric_state
      entity_id: sensor.dark_sky_precip_intensity
      above: 1

  condition:
    - condition: state
      entity_id: group.household
      state: 'home'
    - condition: time
      after: '09:00'
    - condition: state
      entity_id: sun.sun
      state: 'above_horizon'
    - condition: state
      entity_id: binary_sensor.main_floor_occupancy
      state: 'on'
    - condition: state
      entity_id: input_boolean.rainy_day_disable
      state: 'off'
    - condition: state
      entity_id: group.household
      state: 'home'

  action:
    - service: light.turn_on
      entity_id: group.living_room_lamps, light.kitchen_cabinets, light.dining_room_table, light.media_center_lighting, light.hallway_light
      data:
        xy_color: [ 0.5134, 0.4149 ]
        brightness: 50

        ##########################################################
        ## Turn Off First Floor Lights During Rain
        ##########################################################

- alias: Weather - Rain is over First Floor Lights Off

  trigger:
    - platform: numeric_state
      entity_id: sensor.dark_sky_precip_intensity
      below: 1

  condition:
    - condition: state
      entity_id: sun.sun
      state: 'above_horizon'

  action:
    - service: light.turn_off
      entity_id: group.living_room_lamps, light.kitchen_cabinets, light.dining_room_table, light.media_center_lighting, light.hallway_light

        ##########################################################
        ## Turn On _USER2_ Office During Rain
        ##########################################################

- alias: Weather - Rain _USER2_ Office Lights On

  trigger:
    - platform: numeric_state
      entity_id: sensor.dark_sky_precip_intensity
      above: 1

  condition:
    - condition: state
      entity_id: binary_sensor._USER2_office_occupancy
      state: 'on'
    - condition: state
      entity_id: sun.sun
      state: 'above_horizon'
    - condition: state
      entity_id: input_boolean.rainy_day_disable
      state: 'off'
    - condition: state
      entity_id: device_tracker._USER2DEVICE_
      state: 'home'

  action:
    - service: light.turn_on
      entity_id: group._USER2_office, group.stairs
      data:
        brightness: 50

        ##########################################################
        ## Turn Off _USER2_ Office During Rain
        ##########################################################

- alias: Weather - Rain is over _USER2_ Office Lights Off

  trigger:
    - platform: numeric_state
      entity_id: sensor.dark_sky_precip_intensity
      below: 1

  condition:
    - condition: state
      entity_id: sun.sun
      state: 'above_horizon'

  action:
    - service: light.turn_off
      entity_id: group._USER2_office, group.stairs

        ##########################################################
        ## Turn On _USER1_ Office During Rain
        ##########################################################

- alias: Weather - Rain _USER1_ Office Lights On

  trigger:
    - platform: numeric_state
      entity_id: sensor.dark_sky_precip_intensity
      above: 1

  condition:
    - condition: state
      entity_id: binary_sensor.office_occupancy
      state: 'on'
    - condition: state
      entity_id: sun.sun
      state: 'above_horizon'
    - condition: state
      entity_id: input_boolean.rainy_day_disable
      state: 'off'
    - condition: state
      entity_id: device_tracker._USER1DEVICE_
      state: 'home'

  action:
    - service: light.turn_on
      entity_id: light.office_lamp, group.stairs
      data:
        brightness: 30
        xy_color: [0.139,0.081]

        ##########################################################
        ## Turn Off _USER1_ Office During Rain
        ##########################################################

- alias: Weather - Rain is over _USER1_ Office Lights Off

  trigger:
    - platform: numeric_state
      entity_id: sensor.dark_sky_precip_intensity
      below: 1

  condition:
    - condition: state
      entity_id: sun.sun
      state: 'above_horizon'

  action:
    - service: light.turn_off
      entity_id: light.office_lamp, group.stairs
